global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metrics Service
  - job_name: 'metrics-service'
    static_configs:
      - targets: ['host.docker.internal:5005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:5002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database Service
  - job_name: 'database-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Frontend
  - job_name: 'frontend'
    static_configs:
      - targets: [host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:4003']
    metrics_path: '/metrics'
    scrape_interval: 30s 